version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile-prod.txt
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static_volume:/app/static_collected
      - media_volume:/app/media

volumes:
  static_volume:
  media_volume: 