# Generated by Django 5.1a1 on 2025-03-29 05:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('Ad', '0001_initial'), ('Ad', '0002_newscomment'), ('Ad', '0003_newsqrcode'), ('Ad', '0004_sourceqrcode_delete_newsqrcode'), ('Ad', '0005_delete_sourceqrcode'), ('Ad', '0006_weathercache'), ('Ad', '0007_userprofile_comments'), ('Ad', '0008_weathercache_background_image_and_more'), ('Ad', '0006_currencyrate_source_alter_currencyrate_rate_and_more'), ('Ad', '0007_currencyratehistory'), ('Ad', '0008_rename_ad_currency_currenc_2142ef_idx_ad_currency_currenc_b73114_idx_and_more'), ('Ad', '0009_merge_20250328_0112'), ('Ad', '0010_userprofile_ratings'), ('Ad', '0011_remove_userprofile_ratings'), ('Ad', '0012_alter_weathercache_background_image'), ('Ad', '0013_alter_weathercache_background_image')]

    # Отмечаем, что эта миграция может применяться даже если таблицы уже существуют
    run_before = []
    initial = True
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Добавляем операцию для проверки существования таблиц перед их созданием
        migrations.RunPython(
            code=lambda apps, schema_editor: None,
            reverse_code=lambda apps, schema_editor: None,
            atomic=False,
            hints={'target_db': None},
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='backgrounds/', verbose_name='Фоновое изображение')),
            ],
            options={
                'verbose_name': 'Фоновое изображение',
                'verbose_name_plural': 'Фоновые изображения',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=10, verbose_name='Название валюты')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Курс')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('symbol', models.CharField(default='₽', max_length=5, verbose_name='Символ валюты')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Источник данных')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название источника')),
                ('feed_url', models.URLField(max_length=1000, verbose_name='URL RSS канала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный источник')),
            ],
            options={
                'verbose_name': 'Источник новостей',
                'verbose_name_plural': 'Источники новостей',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('image', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на изображение')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='news_backgrounds/', verbose_name='Фоновое изображение')),
                ('link', models.URLField(blank=True, max_length=1000, null=True, unique=True, verbose_name='Ссылка на новость')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ad.newssource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(verbose_name='Лайк')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ad.news', verbose_name='Новость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка новости',
                'verbose_name_plural': 'Оценки новостей',
                'unique_together': {('user', 'news')},
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Ad.news', verbose_name='Новость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий к новости',
                'verbose_name_plural': 'Комментарии к новостям',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('comments', models.ManyToManyField(blank=True, related_name='user_profiles', to='Ad.newscomment', verbose_name='Комментарии пользователя')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('background_image', models.CharField(default='Пасмурно.png', max_length=100)),
            ],
            options={
                'unique_together': {('city', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CurrencyRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=10, verbose_name='Название валюты')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Курс')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время фиксации')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Источник данных')),
            ],
            options={
                'verbose_name': 'История курса валюты',
                'verbose_name_plural': 'История курсов валют',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['currency_name', 'timestamp'], name='Ad_currency_currenc_2142ef_idx')],
            },
        ),
        migrations.RenameIndex(
            model_name='currencyratehistory',
            new_name='ad_currency_currenc_b73114_idx',
            old_name='Ad_currency_currenc_2142ef_idx',
        ),
        migrations.AlterModelTable(
            name='currencyratehistory',
            table='ad_currencyratehistory',
        ),
        migrations.AlterField(
            model_name='weathercache',
            name='background_image',
            field=models.CharField(default='Пасмурно.png', max_length=100),
        ),
    ]
