# Generated by Django 5.1a1 on 2025-03-08 22:16

# Миграция для создания основных моделей проекта:
# - BackgroundImage - модель для хранения фоновых изображений
# - CurrencyRate - модель для курсов валют
# - NewsSource - модель для источников новостей
# - News - модель для самих новостей
# - UserProfile - модель профиля пользователя
# - NewsRating - модель для хранения лайков/дизлайков новостей

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='backgrounds/', verbose_name='Фоновое изображение')),
            ],
            options={
                'verbose_name': 'Фоновое изображение',
                'verbose_name_plural': 'Фоновые изображения',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=10, verbose_name='Название валюты')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('symbol', models.CharField(default='₽', max_length=5, verbose_name='Символ валюты')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название источника')),
                ('feed_url', models.URLField(max_length=1000, verbose_name='URL RSS канала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный источник')),
            ],
            options={
                'verbose_name': 'Источник новостей',
                'verbose_name_plural': 'Источники новостей',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('image', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на изображение')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='news_backgrounds/', verbose_name='Фоновое изображение')),
                ('link', models.URLField(blank=True, max_length=1000, null=True, unique=True, verbose_name='Ссылка на новость')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ad.newssource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='NewsRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(verbose_name='Лайк')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ad.news', verbose_name='Новость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка новости',
                'verbose_name_plural': 'Оценки новостей',
                'unique_together': {('user', 'news')},
            },
        ),
    ]
