# Generated by Django 5.1a1 on 2025-03-09 00:25

# Миграция для добавления модели NewsQRCode:
# - Создает модель для хранения QR-кодов для новостей
# - Позволяет генерировать и сохранять QR-коды, связанные с конкретными новостями
# - Каждая новость может иметь только один QR-код (отношение один-к-одному)
# - QR-коды сохраняются в директории 'news_qr_codes/'

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad', '0002_newscomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_qr_codes/', verbose_name='QR-код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='Ad.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'QR-код новости',
                'verbose_name_plural': 'QR-коды новостей',
            },
        ),
    ]
