# Generated by Django 5.1a1 on 2025-03-09 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad', '0003_newsqrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='source_qr_codes/', verbose_name='QR-код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='Ad.newssource', verbose_name='Источник новостей')),
            ],
            options={
                'verbose_name': 'QR-код источника',
                'verbose_name_plural': 'QR-коды источников',
            },
        ),
        migrations.DeleteModel(
            name='NewsQRCode',
        ),
    ]
