# Generated by Django 5.1a1 on 2025-03-09 18:37

# Миграция для удаления модели SourceQRCode:
# - Полностью удаляет модель SourceQRCode
# - Отказ от функциональности QR-кодов в приложении
# - Часть процесса упрощения структуры базы данных

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ad', '0004_sourceqrcode_delete_newsqrcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceQRCode',
        ),
    ]
