# Generated by Django 5.1a1 on 2025-03-25 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad', '0005_delete_sourceqrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Источник данных'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
    ]
