# Generated by Django 5.1a1 on 2025-03-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad', '0005_delete_sourceqrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('city', 'date')},
            },
        ),
    ]
