# Generated by Django 5.1a1 on 2025-03-25 06:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad', '0006_currencyrate_source_alter_currencyrate_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=10, verbose_name='Название валюты')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Курс')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время фиксации')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Источник данных')),
            ],
            options={
                'verbose_name': 'История курса валюты',
                'verbose_name_plural': 'История курсов валют',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['currency_name', 'timestamp'], name='Ad_currency_currenc_2142ef_idx')],
            },
        ),
    ]
