# Generated by Django 5.1a1 on 2025-03-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad', '0006_weathercache'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='Ad.newscomment', verbose_name='Комментарии пользователя'),
        ),
    ]
