# Generated by Django 5.1a1 on 2025-03-25 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ad', '0007_currencyratehistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='currencyratehistory',
            new_name='ad_currency_currenc_b73114_idx',
            old_name='Ad_currency_currenc_2142ef_idx',
        ),
        migrations.AlterModelTable(
            name='currencyratehistory',
            table='ad_currencyratehistory',
        ),
    ]
