# Generated by Django 5.1a1 on 2025-03-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad', '0007_userprofile_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathercache',
            name='background_image',
            field=models.CharField(default='Пасмурно.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='weathercache',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weathercache',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weathercache',
            name='icon',
            field=models.CharField(max_length=10),
        ),
    ]
