# Generated by Django 5.1a1 on 2025-03-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ad', '0008_rename_ad_currency_currenc_2142ef_idx_ad_currency_currenc_b73114_idx_and_more'),
        ('Ad', '0008_weathercache_background_image_and_more'),
    ]

    operations = [
    ]
