# Generated by Django 5.1a1 on 2025-03-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad', '0009_merge_20250328_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='Ad.newsrating', verbose_name='Оценки пользователя'),
        ),
    ]
